### ISSUE TITLE
Support for LLVM 12.0.1

### ISSUE THREAD

**Issue by marcauberer** [KyleMayes/install-llvm-action#16]
Hi,
please add the support for v12.0.1, which was released recently ...

**Comment by KyleMayes** [comment]
Added in `v1.4.1`.

Seems like the Clang / LLVM release process is still manual, they forgot to release binaries for macOS and Linux.

I added support for using `12.0.1-rc4` for Linux as a workaround because that is the final RC that became `12.0.1`.
However, there weren't any macOS binaries for `12.0.1-rc4` either so `12.0.1` won't be available on that platform.

**Comment by marcauberer** [comment]
Perfect, thank you!

**Comment by marcauberer** [comment]
@KyleMayes FYI: Now there is an archive for Ubuntu 16.04 uploaded to the release (`clang+llvm-12.0.1-x86_64-linux-gnu-ubuntu-16.04.tar.xz`)
