### ISSUE TITLE
llvm-lit not bundled

### ISSUE THREAD

**Issue by deadalnix** [KyleMayes/install-llvm-action#50]
Hi,

LLVM comes with a testing framework in python: llvm-lit . Unfortunately, this way of deploying llvm does not contains said utility.

**Comment by makslevental** [comment]
yea i was going to ask the same thing but about `FileCheck` itself, note that lit is available through pypi https://pypi.org/project/lit/ but that doesn't really matter because FileCheck isn't.

**Comment by FreeMasen** [comment]
This action uses the release artifacts hosted on [llvm-project](https://blog.rust-lang.org/inside-rust/2023/10/06/polonius-update.html)'s repository page. These releases are built and packaged by volunteers, so the existence of the release and its contents is not guaranteed. If you are interested in augmenting what is provided, you'll either getting commit rights on the llvm-project and uploading an artifact that meets your needs or you'll need to built it and host it somewhere. You can use the [`download-url`](https://github.com/KyleMayes/install-llvm-action#download-url) configuration to point the action to an alternate asset.

**Comment by KyleMayes** [comment]
Yes, this action just serves as a convenience for downloading binary assets from LLVM's GitHub repository and there is no guarantee for what is inside these assets or whether assets are available at all for certain combinations of platform and LLVM version.

As of the newly released [`v2.0.0`](https://github.com/KyleMayes/install-llvm-action/blob/master/CHANGELOG.md#200---2024-03-31), these options would be of note for providing custom sets of binaries to be downloaded and extracted by this action:

- `force-url` &ndash; a full URL to a binary assets file (bypasses this action's logic for constructing such a URL)
- `mirror-url` &ndash; a base URL to download binaries from instead of using GitHub (it's assumed the binaries available on this mirror match what can be found on the [releases page for `llvm/llvm-project`](https://github.com/llvm/llvm-project/releases)
