### ISSUE TITLE
Caching does not Improve performance

### ISSUE THREAD

**Issue by WalterSmuts** [KyleMayes/install-llvm-action#56]
See https://github.com/hylo-lang/hylo/pull/957 for a bit more detail. I could be doing something wrong, so please verify. 

I suspect the caching servers have been nerfed. May be worth it to drop mentions of the caching in the documentation.

**Comment by KyleMayes** [comment]
Caching the binaries is kind of pointless now that Clang and LLVM binaries are hosted on GitHub itself.

At one point the binaries were hosted by the LLVM project and they complained about projects like this downloading the binaries all the time instead of caching them which was costing them a good bit of money.

 Now Microsoft is paying the bills either way and I did notice that caching is pretty slow, so I've left the caching option in place but added a note that it probably shouldn't be used in the `README.md` and removed the caching example to dissuade casual usage.
